{% set name = "openlineage-dbt" %}
{% set version = "1.25.0" %}
{% set python_min = python_min|default("3.9") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c1b4be966a5ee49f5e79509b25c83e2bd91a74c43f97ea1f2d9cbe6ce5c14f57

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - tqdm >=4.62.0
    - openlineage-integration-common =={{ version }}

test:
  imports:
    - openlineage.common.provider.dbt
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip
    - dbt-core >=1.3.0

about:
  summary: OpenLineage integration with dbt
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - conda-forge/openlineage-integration-common
    - conda-forge/openlineage-sql
    - conda-forge/openlineage-python
