{% set name = "openlineage-dbt" %}
{% set version = "1.31.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9dafbcb863b63a37228863597f40c758a8fdff7e8f5022a623a0ab6ebb8a6f7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - tqdm >=4.62.0
    - openlineage-integration-common =={{ version }}

test:
  imports:
    - openlineage.common.provider.dbt
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - dbt-core >=1.3.0

about:
  summary: OpenLineage integration with dbt
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
    - millsks
    - conda-forge/openlineage-integration-common
    - conda-forge/openlineage-sql
    - conda-forge/openlineage-python
