{% set name = "openlineage-dbt" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openlineage-dbt-{{ version }}.tar.gz
  sha256: b35c4a9441fbf4dadc42c448c92807e35b196de265d5390a6874c3814f2f698b

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - tqdm >=4.62.0
    - openlineage-integration-common =={{ version }}

test:
  imports:
    - openlineage.common.provider.dbt
  commands:
    - pip check
  requires:
    - pip
    - dbt-core >=1.3.0

about:
  summary: OpenLineage integration with dbt
  home: https://github.com/OpenLineage/OpenLineage
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
extra:
  recipe-maintainers:
    - rxm7706
